use_frameworks!
platform :ios, '10.0'

source 'git@github.com:zhang232425/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false

target 'ZJLocalAuth_Example' do
  pod 'ZJLocalAuth', :path => '../'

end
